/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'WorkflowStream': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'WorkflowMonitor': EventHandler<never, never>
    'TriggerBackgroundJob': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'job-trigger'; data: never }>
    'ScheduledMaintenance': CronHandler<never>
    'ListWorkflows': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'JobTriggerHandler': EventHandler<never, never>
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetMetrics': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetExecutionStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ExecuteWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'workflow-execute'; data: never }>
    'CreateWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'workflow-created'; data: never }>
    'BackgroundProcessor': EventHandler<never, { topic: 'job-completed'; data: never } | { topic: 'job-failed'; data: never }>
    'WorkflowOptimizer': EventHandler<never, never>
    'WorkflowExecutor': EventHandler<never, { topic: 'workflow-execution-completed'; data: never } | { topic: 'workflow-execution-failed'; data: never }>
    'WorkflowAnalyzer': EventHandler<never, { topic: 'workflow-analyzed'; data: never }>
  }
    
}